provider: ibm
category: devops
solution_name: ansible-automation-platform
solution_display_name: Ansible Automation Platform
description: IT automation platform for operational efficiency
version: 1.0.0
status: In Review
maintainers:
- name: EO Framework Solutions Team
  email: support@eoframework.com
  role: Solutions Architect
tags:
- platform
- ibm
- automation
- devops
- ansible
requirements:
  prerequisites:
  - IBM Account
  - Administrative Access
  tools:
  - Python 3.8+
  - OpenShift CLI
  - Ansible
  skills:
  - IBM Platform
  - Solution Architecture
  - Container Platforms
repository:
  url: https://github.com/eoframework/public-assets
  type: git
  path: solutions/ibm/devops/ansible-automation-platform
  clone_url: https://github.com/eoframework/public-assets.git
access:
  browse_url: https://github.com/eoframework/public-assets/tree/main/solutions/ibm/devops/ansible-automation-platform
  raw_url: https://raw.githubusercontent.com/eoframework/public-assets/main/solutions/ibm/devops/ansible-automation-platform
  latest_tag: ibm/devops/ansible-automation-platform-v1.0.0
support:
  website: https://eoframework.com/solutions
  email: support@eoframework.com
  documentation: https://docs.eoframework.com/solutions/ibm/devops/ansible-automation-platform
